<a href="[field:arcurl/]" title="[field:text/]">
							<li>
								<div class="w-lckj-top1 lf"><img src="[field:litpic/]" /></div>
								<div class="w-lckj-top3 lf of">
									<div class="w-lckj-top-title">[field:title/]</div>
									<div class="w-lckj-top-txt1">地址：[field:city/][field:detail_address/]</div>
									<div class="w-lckj-top-txt2 of">
										<div class="w-lckj-top-txt2-lf lf">联系人：[field:contacts/]</div>
									</div>
								</div>
								<div class="w-lckj-top4 rg">[field:city/]</div>
						</li>
					</a>