<a href="[field:imgsrc/]" title="[field:text/]">
							<li>
								<div class="w-lckj-top1 lf">[field:imgsrc/]</div>
								<div class="w-lckj-top3 lf of">
									<div class="w-lckj-top-title">金田园茶业有限公司</div>
									<div class="w-lckj-top-txt1">地址：广东省广州市番禺祈福鼎泰茶博城6栋7,8,15,16号</div>
									<div class="w-lckj-top-txt2 of">
										<div class="w-lckj-top-txt2-lf lf">联系人：陈先生</div>
									</div>
								</div>
								<div class="w-lckj-top4 rg">广州市</div>
						</li>
					</a>