
<field:name itemname="申请人姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="固定电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:tel itemname="移动电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:qq_num itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq_num>

<field:place itemname="加盟地区" autofield="1" type="select" isnull="true" default="请选择"  maxlength="250" page="">
</field:place>

