
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='公司' ischannel='1' link='content_i_list.php?channelid=18' linkadd='album_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='茶文化交流图集' ischannel='1' link='content_i_list.php?channelid=19' linkadd='album_add.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='我的商品' ischannel='1' link='content_i_list.php?channelid=20' linkadd='album_add.php?channelid=20' channelid='20' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
