{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/170113/1-1F1131A316.jpg' text='阿萨德' width='115' height='115'} /uploads/allimg/170113/1-1F1131A316.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170113/1-1F1131A319.jpg' text='阿萨德' width='115' height='115'} /uploads/allimg/170113/1-1F1131A319.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170113/1-1F1131A328.jpg' text='阿萨德' width='688' height='514'} /uploads/allimg/170113/1-1F1131A328.jpg {/dede:img}
