<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170113/1-1F1131A316.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/170113/1-1F1131A316.jpg";
$z[1][4]['text']="阿萨德";
$z[1][4]['width']="115";
$z[1][4]['height']="115";
$z[2]=Array("img"," /uploads/allimg/170113/1-1F1131A319.jpg ",247,399);
$z[2][4]['ddimg']="/uploads/allimg/170113/1-1F1131A319.jpg";
$z[2][4]['text']="阿萨德";
$z[2][4]['width']="115";
$z[2][4]['height']="115";
$z[3]=Array("img"," /uploads/allimg/170113/1-1F1131A328.jpg ",401,553);
$z[3][4]['ddimg']="/uploads/allimg/170113/1-1F1131A328.jpg";
$z[3][4]['text']="阿萨德";
$z[3][4]['width']="688";
$z[3][4]['height']="514";

?>