<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:detail_address itemname="详细地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:detail_address>
<field:contacts itemname="承办单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:contacts>
<field:qq_num itemname="活动时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:qq_num>

<field:zhuban itemname="主办单位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuban>

<field:serport itemname="支持" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:serport>

<field:hold_city itemname="举办城市" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hold_city>
