<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170116/1-1F116151K9.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/170116/1-1F116151K9.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="124";
$z[1][4]['height']="124";
$z[2]=Array("img"," /uploads/allimg/170116/1-1F116151K9-50.jpg ",238,387);
$z[2][4]['ddimg']="/uploads/allimg/170116/1-1F116151K9-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="124";
$z[2][4]['height']="124";
$z[3]=Array("img"," /uploads/allimg/170116/1-1F116151K9-51.jpg ",389,538);
$z[3][4]['ddimg']="/uploads/allimg/170116/1-1F116151K9-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="688";
$z[3][4]['height']="514";
$z[4]=Array("img"," /uploads/allimg/170116/1-1F116151P0.jpg ",540,683);
$z[4][4]['ddimg']="/uploads/allimg/170116/1-1F116151P0.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="134";
$z[4][4]['height']="101";
$z[5]=Array("img"," /uploads/allimg/170116/1-1F116151P0.png ",685,828);
$z[5][4]['ddimg']="/uploads/allimg/170116/1-1F116151P0.png";
$z[5][4]['text']="";
$z[5][4]['width']="688";
$z[5][4]['height']="514";

?>