<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:trueprice itemname="价格" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
	
<field:units itemname="规格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:units>	
		
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
<field:gongyi itemname="工艺" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="生茶,熟茶"  maxlength="250" page="">
</field:gongyi>
<field:type itemname="类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="饼茶"  maxlength="250" page="">
</field:type>
<field:environment itemname="环境" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=" 清洁、通风、避光、阴凉、干燥、无异味、无污染"  maxlength="250" page="">
</field:environment>
<field:period itemname="保质期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="在符合贮存的环境中适合长期保存"  maxlength="250" page="">
</field:period>
<field:package itemname="包装" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="礼品包装"  maxlength="250" page="">
</field:package>
<field:product_place itemname="产地" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="云南省临沧市勐库"  maxlength="250" page="">
</field:product_place>