
<field:name itemname="申请人姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="固定电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:tel itemname="移动电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:qq_num itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq_num>

<field:place itemname="加盟地区" autofield="1" type="select" isnull="true" default="请选择"  maxlength="250" page="">
</field:place>


<field:chuanzhen itemname="传真" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:chuanzhen>

<field:detail_address itemname="详细地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:detail_address>

<field:e_mail itemname="E-mail" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:e_mail>

<field:xz itemname="经营性质" autofield="1" type="radio" isnull="true" default="私营"  maxlength="250" page="">
</field:xz>

<field:work_time itemname="茶行业从业时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:work_time>

<field:your_product itemname="曾经营和现经营产品" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:your_product>

<field:puer_time itemname="普洱茶从业时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:puer_time>

<field:know itemname="您对合和昌的了解情况" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:know>
