<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
<field:trueprice itemname="价格" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
	
<field:units itemname="规格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:units>	
	
<field:vocation itemname="行业" autofield="1" notsend="0"type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:vocation>	
<field:infotype itemname="信息类型" autofield="1" notsend="0" type="stepselect" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:infotype>	
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
