<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170112/1-1F112151556.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/170112/1-1F112151556.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="700";
$z[1][4]['height']="467";
$z[2]=Array("img"," /uploads/allimg/170112/1-1F112151604.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/170112/1-1F112151604.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="115";
$z[2][4]['height']="115";
$z[3]=Array("img"," /uploads/allimg/170112/1-1F112151607.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/170112/1-1F112151607.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="321";
$z[3][4]['height']="435";

?>