<li>
					<div class="w-news-tp of">
						<div class="w-news-tp1 lf"><a href="[field:arcurl/]" title="">[field:image/]</a></div>
						<div class="w-news-tp2 lf">
							<div class="w-news-tp21 cl"><a href="[field:arcurl/]" title="">[field:title/]</a></div>
							<div class="w-news-tp22 cl">[field:body/]</div>
						</div>
						<div class="w-news-tp3 rg">[field:pubdate function="GetDateMK(@me)"/]</div>
					</div>
				</li>