<?php
$z[0]=Array("litpic","",68,83);
$z[1]=Array("pubdate","",154,196);
$z[1][4]['function']="GetDateMK(@me)";
$z[2]=Array("arcurl","",219,234);
$z[3]=Array("title","",265,279);
$z[4]=Array("arcurl","",532,547);
$z[5]=Array("title","",580,594);
$z[6]=Array("litpic","",1021,1036);
$z[7]=Array("pubdate","",1107,1149);
$z[7][4]['function']="GetDateMK(@me)";
$z[8]=Array("arcurl","",1172,1187);
$z[9]=Array("title","",1218,1232);
$z[10]=Array("arcurl","",1485,1500);
$z[11]=Array("title","",1533,1547);

?>