　　
    　　
        <div class="unified-title">
            <h1>[field:title/]</h1>
            <div class="com-titlef">
                <ul>
                    <li><a href="/" class="active">首页</a></li>
                    <li><i></i></li>
                    <li>[field:title/]</li>
                </ul>
            </div>
            <div class="com-titrig">
                <div class="bshare-custom"><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博"
                                                                                          class="bshare-sinaminiblog"></a><a
                        title="分享到人人网" class="bshare-renren"></a><a title="分享到腾讯微博" class="bshare-qqmb"></a><a
                        title="分享到网易微博" class="bshare-neteasemb"></a><a title="更多平台"
                                                                        class="bshare-more bshare-more-icon more-style-addthis"></a><span
                        class="BSHARE_COUNT bshare-share-count">0</span></div>
                <script type="text/javascript" charset="utf-8"
                        src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
                <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
            </div>
        </div>

        <div class="compr-deles">
            <div class="compr-text">
                [field:body/]
            </div>
        </div>