{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/170113/1-1F113164929.jpg' text='阿萨德' width='115' height='115'} /uploads/allimg/170113/1-1F113164929.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170113/1-1F113164933.jpg' text='账号' width='115' height='115'} /uploads/allimg/170113/1-1F113164933.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170113/1-1F113164935.jpg' text='大花洒' width='115' height='115'} /uploads/allimg/170113/1-1F113164935.jpg {/dede:img}
