<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170113/1-1F113164929.jpg ",93,247);
$z[1][4]['ddimg']="/uploads/allimg/170113/1-1F113164929.jpg";
$z[1][4]['text']="阿萨德";
$z[1][4]['width']="115";
$z[1][4]['height']="115";
$z[2]=Array("img"," /uploads/allimg/170113/1-1F113164933.jpg ",249,400);
$z[2][4]['ddimg']="/uploads/allimg/170113/1-1F113164933.jpg";
$z[2][4]['text']="账号";
$z[2][4]['width']="115";
$z[2][4]['height']="115";
$z[3]=Array("img"," /uploads/allimg/170113/1-1F113164935.jpg ",402,556);
$z[3][4]['ddimg']="/uploads/allimg/170113/1-1F113164935.jpg";
$z[3][4]['text']="大花洒";
$z[3][4]['width']="115";
$z[3][4]['height']="115";

?>