<?php
$z[0]=Array("include","",681,716);
$z[0][4]['filename']="head.htm";
$z[1]=Array("artlist","\r\n					<li>\r\n						<div class=\"w_ppzs_pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></div>\r\n						<div class=\"w_ppzs_tit\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n						<div class=\"w_ppzs_txt\">[field:body function='cn_substr(html2text(@me),200)'/]...</div>\r\n					</li>\r\n				",5412,5796);
$z[1][4]['typeid']="29";
$z[1][4]['addfields']="body";
$z[1][4]['channelid']="19";
$z[1][4]['row']="6";
$z[2]=Array("artlist","\r\n			<div class=\"w_qk_lf lf of\">\r\n				<div class=\"w_qk_img lf\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></div>\r\n				<div class=\"w_qk_txt lf\">\r\n					<div class=\"w_qk_txt1\">合和昌期刊</div>\r\n					<div class=\"w_qk_txt2\">[field:title/]</div>\r\n					<div class=\"w_qk_txt3\">期</div>\r\n				</div>\r\n			</div>\r\n            ",5909,6349);
$z[2][4]['row']="1";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="0,1";
$z[2][4]['typeid']="30";
$z[2][4]['channelid']="1";
$z[2][4]['orderway']="asc";
$z[3]=Array("artlist","\r\n                        <li>\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a>\r\n                            <div class=\"w_qk_title\"><a href=\"[field:arcurl/]\">合和昌期刊  第[field:title/]期</a></div>\r\n                        </li>\r\n                    ",6413,6816);
$z[3][4]['channelid']="1";
$z[3][4]['orderby']="pubdate";
$z[3][4]['typeid']="30";
$z[3][4]['row']="6";
$z[3][4]['limit']="1,7";
$z[3][4]['orderway']="asc";
$z[4]=Array("include","",6879,6916);
$z[4][4]['filename']="footer.htm";

?>