<?php
$z[0]=Array("include","",615,650);
$z[0][4]['filename']="head.htm";
$z[1]=Array("artlist","\r\n				<li>\r\n					<a href=\"\">\r\n					<div class=\"weekly-img\">\r\n						<img src=\"[field:litpic/]\" />\r\n					</div>\r\n					<div class=\"weekly-text\">\r\n						<p>合和昌期刊  第[field:title/]期</p>\r\n						<a href=\"[field:file_path/]\" class=\"down-btn\">下载期刊</a>\r\n					</div>\r\n					</a>\r\n				</li>\r\n				",1883,2303);
$z[1][4]['row']="8";
$z[1][4]['addfields']="file_path";
$z[1][4]['orderby']="pubdate";
$z[1][4]['typeid']="30";
$z[1][4]['channelid']="1";
$z[1][4]['orderway']="asc";
$z[2]=Array("include","",2368,2405);
$z[2][4]['filename']="footer.htm";

?>