
<field:name itemname="申请人姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="固定电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:tel itemname="移动电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:qq_num itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq_num>

<field:place itemname="加盟地区" autofield="1" type="select" isnull="true" default="请选择,北京,天津,上海,重庆,黑龙江,吉林,辽宁,河北,山西,青海,山东,河南,江苏,安徽,浙江,福建,江西,湖南,湖北,广东,台湾,海南,陕西,甘肃,四川,贵州,云南,新疆维吾尔自治区,内蒙古自治区,西藏自治区, 宁夏回族自治区,广西壮族自治区,香港特别行政区,澳门特别行政区"  maxlength="250" page="">
</field:place>



<field:chuanzhen itemname="传真" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:chuanzhen>

<field:detail_address itemname="详细地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:detail_address>

<field:e_mail itemname="E-mail" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:e_mail>

<field:xz itemname="经营性质" autofield="1" type="radio" isnull="true" default="私营,合资,经营模式"  maxlength="250" page="">
</field:xz>



<field:work_time itemname="茶行业从业时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:work_time>

<field:your_product itemname="曾经营和现经营产品" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:your_product>

<field:puer_time itemname="普洱茶从业时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:puer_time>

<field:know itemname="您对合和昌的了解情况" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:know>

<field:company itemname="公司全称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:local_brand itemname="所在地注意茶叶品牌" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:local_brand>

<field:person itemname="法定代表人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:person>

<field:plan itemname="加盟经营计划" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:plan>
