<?php
$z[0]=Array("include","",683,718);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",1994,2017);
$z[1][4]['name']="hot_line";
$z[2]=Array("global","",2056,2086);
$z[2][4]['name']="company_address";
$z[3]=Array("arclist","\r\n		        	<div class=\"w-lxwm4\">[field:image/]</div>\r\n				",2098,2195);
$z[3][4]['row']="1";
$z[4]=Array("global","",2280,2306);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("artlist","\r\n					<div class=\"w_cu_box lf\">\r\n						<div class=\"w_cu_pic\"><img src=\"[field:litpic/]\" /></div>\r\n						<div class=\"w_cu_tit\">[field:title/]</div>\r\n						<div class=\"w_cu_tel\">电话：<strong>[field:qq_num/]</strong></div>\r\n						<div class=\"w_cu_tel\">传真：<strong>[field:contacts/]</strong></div>\r\n						<div class=\"w_cu_add\">地址：[field:detail_address/]</div>\r\n						<div class=\"w_cu_map of tc\"><a href=\"#\">查看地图位置</a></div>\r\n					</div>\r\n				",2374,2953);
$z[5][4]['typeid']="28";
$z[5][4]['addfields']="detail_address,contacts,qq_num";
$z[5][4]['channelid']="18";
$z[5][4]['pagesize']="10";
$z[6]=Array("include","",3036,3072);
$z[6][4]['filename']="footer.htm\"";

?>