{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/170112/1-1F112164J4.jpg' text='' width='688' height='514'} /uploads/allimg/170112/1-1F112164J4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170112/1-1F112164J4-50.jpg' text='' width='688' height='514'} /uploads/allimg/170112/1-1F112164J4-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170112/1-1F112164J5.jpg' text='' width='134' height='101'} /uploads/allimg/170112/1-1F112164J5.jpg {/dede:img}
