<div class="w_cu_box lf">
						<div class="w_cu_pic"><img src="[field:litpic/]" /></div>
						<div class="w_cu_tit">[field:title/]</div>
						<div class="w_cu_tel">电话：<strong>[field:qq_num/]</strong></div>
						<div class="w_cu_tel">传真：<strong>[field:contacts/]</strong></div>
						<div class="w_cu_add">地址：[field:detail_address/]</div>
						<div class="w_cu_map of tc"><a href="#">查看地图位置</a></div>
					</div>