　　[field:body function='cn_substr(@me,330)'/]
    　　
        <div class="unified-title">
            <h1>{dede:field.title typeid='1'/}</h1>
            <div class="com-titlef">
                <ul>
                    <li><a href="/" class="active">首页</a></li>
                    <li><i></i></li>
                    <li>{dede:field.title/}</li>
                </ul>
            </div>
            <div class="com-titrig">
                <div class="bshare-custom"><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博"
                                                                                          class="bshare-sinaminiblog"></a><a
                        title="分享到人人网" class="bshare-renren"></a><a title="分享到腾讯微博" class="bshare-qqmb"></a><a
                        title="分享到网易微博" class="bshare-neteasemb"></a><a title="更多平台"
                                                                        class="bshare-more bshare-more-icon more-style-addthis"></a><span
                        class="BSHARE_COUNT bshare-share-count">0</span></div>
                <script type="text/javascript" charset="utf-8"
                        src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
                <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
            </div>
        </div>

        <div class="compr-deles">
            <div class="compr-text">
                {dede:field.body/}
                <p>
                    勐海合和昌茶业有限公司成立于2010年，座落于被誉为“普洱第一县”的原生态普洱茶之乡——勐海县境内，是一个独具新起点、高定位，集研发、生产、销售、服务为一体的特色茶企业,是一家享誉全国的高端普洱茶品牌茶企。</p>
                <p>
                    从2002年开始，品牌创始人深入云南普洱茶产区，在资深人士的引领指导下，经过多年对普洱茶的产区品质研究、产品生产研发以及市场摸索累积，于2010年正式成立了“合和昌”品牌，并在普洱茶圣地——云南勐海逐步建成生产基地及研发接待中心，在全国茶业最大集散地——广州芳村设立品牌运营中心、体验中心及全国配送中心。</p>
            </div>
        </div>