<?php
$z[0]=Array("global","",252,279);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","(@me==\"\")? @me=\" class='active'\":@me=\"\";",281,371);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n                <li>\r\n                    <a href=\"[field:typelink/]\">\r\n                        <span>[field:description /]</span>\r\n                        <p>[field:typename/]</p>\r\n                    </a>\r\n                </li>\r\n                ",517,902);
$z[2][4]['type']="top";
$z[2][4]['row']="9";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='active'><span></span>~typename~</a></li>";

?>