<?php
$z[0]=Array("include","",681,716);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",918,947);
$z[1][4]['name']="typename";
$z[2]=Array("field","",1090,1119);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n				<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n				",1993,2175);
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='active'><a href='~typeurl~'>~typename~</a></li>";
$z[4]=Array("productimagelist","\r\n								<li>\r\n									<a href=\"#\"><img src=\"[field:imgsrc/]\" alt=\"[field:text/]\"  width=\"700\" height=\"467\" /></a>\r\n								</li>\r\n								",3347,3535);
$z[5]=Array("productimagelist","\r\n									<li>\r\n										<i class=\"arr2\"></i><img src=\"[field:imgsrc/]\" alt=\"[field:text/]\"  width=\"154\" height=\"103\"  />\r\n									</li>\r\n								",3651,3847);
$z[6]=Array("field","",6777,6796);
$z[6][4]['name']="title";
$z[7]=Array("field","",6833,6851);
$z[7][4]['name']="city";
$z[8]=Array("field","",6880,6902);
$z[8][4]['name']="contacts";
$z[9]=Array("field","",6928,6946);
$z[9][4]['name']="city";
$z[10]=Array("field","",6946,6974);
$z[10][4]['name']="detail_address";
$z[11]=Array("field","",7033,7051);
$z[11][4]['name']="city";
$z[12]=Array("field","",7165,7185);
$z[12][4]['name']="qq_num";
$z[13]=Array("field","",7354,7372);
$z[13][4]['name']="body";
$z[14]=Array("include","",7550,7587);
$z[14][4]['filename']="footer.htm";

?>