<?php
$z[0]=Array("include","",681,716);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",918,947);
$z[1][4]['name']="typename";
$z[2]=Array("field","",1090,1119);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n				<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n				",1993,2175);
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='active'><a href='~typeurl~'>~typename~</a></li>";
$z[4]=Array("include","",3081,3118);
$z[4][4]['filename']="footer.htm";

?>