<?php
$z[0]=Array("include","",681,716);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",918,947);
$z[1][4]['name']="typename";
$z[2]=Array("field","",1090,1119);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n				<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n				",1993,2175);
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='active'><a href='~typeurl~'>~typename~</a></li>";
$z[4]=Array("artlist","\r\n	            	<a href=\"[field:arcurl/]\" title=\"[field:text/]\">\r\n							<li>\r\n								<div class=\"w-lckj-top1 lf\"><img src=\"[field:litpic/]\" /></div>\r\n								<div class=\"w-lckj-top3 lf of\">\r\n									<div class=\"w-lckj-top-title\">[field:title/]</div>\r\n									<div class=\"w-lckj-top-txt1\">地址：[field:city/][field:detail_address/]</div>\r\n									<div class=\"w-lckj-top-txt2 of\">\r\n										<div class=\"w-lckj-top-txt2-lf lf\">联系人：[field:contacts/]</div>\r\n									</div>\r\n								</div>\r\n								<div class=\"w-lckj-top4 rg\">[field:city/]</div>\r\n						</li>\r\n					</a>\r\n					",2984,3683);
$z[4][4]['typeid']="27";
$z[4][4]['addfields']="city,detail_address,contacts";
$z[4][4]['channelid']="2";
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",3806,3853);
$z[5][4]['istitem']="pre,nex";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",4077,4114);
$z[6][4]['filename']="footer.htm";

?>