<?php
$z[0]=Array("include","",682,717);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",918,947);
$z[1][4]['name']="typename";
$z[2]=Array("field","",1091,1120);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n					<li><a href='[field:typeurl/]'><span>[field:typename/]</span></a></li>\r\n				",1976,2185);
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='active'><a href='~typeurl~'><span>~typename~</span></a></li>";
$z[4]=Array("list","\r\n		    	<li>\r\n		    		<div class=\"w-news-tp of\">\r\n			        	<div class=\"w-news-tp1 lf\"><a href=\"[field:arcurl/]\" title=\"\">[field:image/]</a></div>\r\n			            <div class=\"w-news-tp2 lf\">\r\n			            	<div class=\"w-news-tp21 cl\"><a href=\"[field:arcurl/]\" title=\"\">[field:title/]</a></div>\r\n			                <div class=\"w-news-tp22 cl\">[field:description /]</div>\r\n			            </div>\r\n			            <div class=\"w-news-tp3 rg\">[field:pubdate function=\"GetDateMK(@me)\"/]</div>\r\n		            </div>\r\n		        </li>\r\n				",2270,2866);
$z[4][4]['channelid']="1";
$z[4][4]['pagesize']="10";
$z[4][4]['typeid']="2";
$z[5]=Array("pagelist","",2956,3003);
$z[5][4]['istitem']="pre,nex";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",3063,3100);
$z[6][4]['filename']="footer.htm";

?>