<?php
$z[0]=Array("include","",614,649);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",863,892);
$z[1][4]['name']="typename";
$z[2]=Array("field","",1036,1065);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n					<dd><a href=\"[field:typeurl/]\" val=\"xxl\" class=\"series\">[field:typename/]</a></dd>\r\n				",2632,2767);
$z[3][4]['typeid']="4";
$z[4]=Array("arclist","\r\n			<div class=\"proclist-box\">\r\n				<a href=\"[field:arcurl/]\">\r\n				<div class=\"proclist-img\"><img src=\"[field:litpic/]\"></div>\r\n				<P>【[field:title/]】<span>[field:pubdate function='strftime(\"%Y\",@me)'/]</span></P>\r\n				</a>\r\n			</div>\r\n		",2863,3180);
$z[4][4]['typeid']="4";
$z[4][4]['pagesize']="6";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("include","",3539,3576);
$z[5][4]['filename']="footer.htm";

?>