<?php
$z[0]=Array("include","",614,649);
$z[0][4]['filename']="head.htm";
$z[1]=Array("productimagelist","\r\n									<li>\r\n										<a href=\"#\" target=\"_blank\"><img width=\"700\" height=\"467\" src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></a>\r\n									</li>\r\n								",3999,4205);
$z[2]=Array("productimagelist","\r\n									<li><i class=\"arr2\"></i><img width=\"154\" height=\"103\" src=\"[field:imgsrc/]\" /></li>\r\n								",4459,4610);
$z[3]=Array("field","",7544,7563);
$z[3][4]['name']="title";
$z[4]=Array("field","",7583,7634);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="strftime(\"%Y\",@me)";
$z[5]=Array("field","",7675,7693);
$z[5][4]['name']="type";
$z[6]=Array("field","",7723,7743);
$z[6][4]['name']="gongyi";
$z[7]=Array("field","</li>\r\n						<li>【规格】 {dede:field.units",7773,7848);
$z[7][4]['name']="product_place";
$z[8]=Array("field","",7878,7929);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="strftime(\"%Y\",@me)";
$z[9]=Array("field","",7962,7987);
$z[9][4]['name']="environment";
$z[10]=Array("field","",8017,8037);
$z[10][4]['name']="period";
$z[11]=Array("field","",8067,8086);
$z[11][4]['name']="title";
$z[12]=Array("field","",8140,8163);
$z[12][4]['name']="trueprice";
$z[13]=Array("field","",9152,9170);
$z[13][4]['name']="body";
$z[14]=Array("include","",9445,9482);
$z[14][4]['filename']="footer.htm";

?>